/**
 * Traductions anglaises, indexées par la phrase française.
 *
 * Le français est la langue source : ce fichier ne contient que l'anglais. Une
 * entrée absente n'est pas une erreur — la phrase française s'affiche telle
 * quelle, ce qui vaut mieux qu'une clé nue à l'écran.
 *
 * La première moitié reprend mot pour mot le dictionnaire du web
 * (`frontend/src/lib/dictionnaire-en.ts`) : les deux applications partagent le
 * même vocabulaire métier, et deux traductions divergentes pour « Créances »
 * seraient un défaut, pas une nuance. La seconde moitié rassemble ce qui n'a
 * pas d'équivalent web — l'application mobile a ses propres écrans.
 *
 * `node scripts/verifier-i18n.mjs --details` liste les manques et les orphelines.
 */

export const DICTIONNAIRE_EN: Record<string, string> = {
  // ── Repris du dictionnaire web ─────────────────────────────────────────
  "+ Échéance": "+ Instalment",
  "6 caractères minimum": "6 characters minimum",
  "Acceptée": "Accepted",
  "Actions": "Actions",
  "Adresse": "Address",
  "Adresse (optionnel)": "Address (optional)",
  "Ajouter un client": "Add a customer",
  "Ajouter un produit": "Add a product",
  "Ajoutez au moins un produit avec une quantité et un prix valides.": "Add at least one product with a valid quantity and price.",
  "Ajoutez au moins un produit.": "Add at least one product.",
  "Ajouté rapidement": "Added quickly",
  "Annuler": "Cancel",
  "Apparence": "Appearance",
  "Article": "Item",
  "Articles": "Items",
  "Aucun avis reçu": "No reviews received",
  "Aucun client": "No customers",
  "Aucun produit": "No products",
  "Aucun produit en stock. Ajoutez du stock avant d'enregistrer une vente.": "No product in stock. Add stock before recording a sale.",
  "Aucun retrait": "No withdrawals",
  "Aucune commande": "No orders",
  "Aucune dépense": "No expenses",
  "Aucune notification": "No notifications",
  "Aucune vente": "No sales",
  "Carte et mobile — frais 1,8 %": "Card and mobile — 1.8% fee",
  "Catégorie": "Category",
  "Ce choix est enregistré sur cet appareil uniquement.": "This choice is saved on this device only.",
  "Changer le mot de passe": "Change password",
  "Chaque mois": "Every month",
  "Chaque semaine": "Every week",
  "Chaque trimestre": "Every quarter",
  "Chargement…": "Loading…",
  "Chercher des produits": "Find products",
  "Choisir un produit…": "Choose a product…",
  "Choisir une catégorie…": "Choose a category…",
  "Choisissez la catégorie du produit.": "Choose the product category.",
  "Choisissez une note entre 1 et 5 étoiles.": "Choose a rating between 1 and 5 stars.",
  "Client": "Customer",
  "Client (optionnel)": "Customer (optional)",
  "Client de passage": "Walk-in customer",
  "Clients": "Customers",
  "Commande passée": "Order placed",
  "Commandes": "Orders",
  "Commandes passées par vos clients détaillants": "Orders placed by your retail customers",
  "Commandes reçues": "Orders received",
  "Commentaire (optionnel)": "Comment (optional)",
  "Comptant": "Upfront",
  "Configuration de paiement indisponible.": "Payment configuration unavailable.",
  "Confirmer le nouveau mot de passe": "Confirm the new password",
  "Connexion…": "Signing in…",
  "Continuer": "Continue",
  "Contre-proposer": "Counter-offer",
  "Contre-proposée": "Counter-offered",
  "Créances": "Receivables",
  "Créances clients": "Customer receivables",
  "Créances en cours": "Open receivables",
  "Créances fournisseurs": "Supplier receivables",
  "Création…": "Creating…",
  "Crédit": "Credit",
  "Crédits fournisseurs": "Supplier credit",
  "Créer la commande": "Create order",
  "Date de naissance (optionnel)": "Date of birth (optional)",
  "Date de paiement": "Payment date",
  "Demander le paiement": "Request payment",
  "Déjà payé": "Already paid",
  "Dépenses": "Expenses",
  "Détaillant": "Retailer",
  "Détails": "Details",
  "Email": "Email",
  "Email (optionnel)": "Email (optional)",
  "En attente de réponse": "Awaiting a reply",
  "En cours": "Open",
  "En retard": "Overdue",
  "Encaisser": "Collect",
  "Encaisser une créance": "Collect a receivable",
  "Encaissé": "Collected",
  "Enregistrement…": "Saving…",
  "Enregistrer": "Save",
  "Enregistrer la vente": "Save sale",
  "Enregistrer le produit": "Save product",
  "Enregistrer une transaction": "Record a transaction",
  "Ex : 22901020304": "e.g. 22901020304",
  "Ex : client fidèle, commande régulière…": "e.g. loyal customer, regular order…",
  "Facultatif, mais tant qu'il n'est pas renseigné les retraits sont limités à la fréquence « 1 jour ».": "Optional, but until it is filled in withdrawals are limited to the “1 day” frequency.",
  "Fermer": "Close",
  "Fournisseur": "Supplier",
  "Fournisseur en détail — vous commandez chez les grossistes et vendez à vos clients": "Retail supplier — you order from wholesalers and sell to your customers",
  "Fournisseur en gros — vous recevez et validez les commandes des détaillants": "Wholesale supplier — you receive and approve retailers' orders",
  "Fournisseur externe": "External supplier",
  "Frais à ma charge": "Fees charged to me",
  "Générer le plan": "Generate schedule",
  "Gérer les commandes des détaillants": "Manage retailers' orders",
  "IFU (Identifiant Fiscal Unique)": "TIN (Tax Identification Number)",
  "IFU (Identifiant Fiscal Unique) — si vous l'avez": "TIN (Tax Identification Number) — if you have one",
  "Je paie les frais": "I pay the fees",
  "Je supporte les frais": "I cover the fees",
  "L'opération n'est enregistrée qu'après vérification auprès de la passerelle.": "The operation is only recorded after verification with the gateway.",
  "Le client est débité de": "The customer is charged",
  "Le client paie les frais": "The customer pays the fees",
  "Le détaillant": "The retailer",
  "Le grossiste": "The wholesaler",
  "Le payeur supporte les frais": "The payer covers the fees",
  "Le prix affiché est celui de la commande. Vous pouvez en proposer un autre : le grossiste devra l'accepter pour qu'il s'applique.": "The price shown is the order's. You may offer another: the wholesaler must accept it for it to apply.",
  "Les deux nouveaux mots de passe ne correspondent pas.": "The two new passwords do not match.",
  "Ligne de secours, pour joindre le client quand la première ne répond pas": "Backup line, to reach the customer when the first one does not answer",
  "Lignes": "Lines",
  "Livrée": "Delivered",
  "Mes commandes": "My orders",
  "Message (optionnel)": "Message (optional)",
  "Mobile Money — frais 1,9 %": "Mobile Money — 1.9% fee",
  "Mode": "Method",
  "Mode de paiement": "Payment method",
  "Modification…": "Updating…",
  "Modifier": "Edit",
  "Moitié-moitié": "Split evenly",
  "Montant (FCFA)": "Amount (FCFA)",
  "Montant encaissé (FCFA)": "Amount collected (FCFA)",
  "Montant payé (FCFA)": "Amount paid (FCFA)",
  "Montant total": "Total amount",
  "Montant total des créances": "Total receivables",
  "Montant à encaisser": "Amount to collect",
  "Mot de passe": "Password",
  "Mot de passe actuel": "Current password",
  "Mot de passe mis à jour.": "Password updated.",
  "Nom": "Last name",
  "Nom complet": "Full name",
  "Nom de la boutique": "Shop name",
  "Nom du fournisseur": "Supplier name",
  "Nom du produit": "Product name",
  "Nombre de fois": "Number of times",
  "Notes": "Notes",
  "Notes (optionnel)": "Notes (optional)",
  "Nouveau client": "New customer",
  "Nouveau mot de passe": "New password",
  "Nouveau retrait": "New withdrawal",
  "Nouvelle commande": "New order",
  "Nouvelle vente": "New sale",
  "Numéro Mobile Money": "Mobile Money number",
  "Numéro Mobile Money du client": "Customer's Mobile Money number",
  "Numéro de téléphone du fournisseur": "Supplier phone number",
  "Négociation du prix": "Price negotiation",
  "Obligatoire. Les espaces et tirets sont ignorés.": "Required. Spaces and dashes are ignored.",
  "Opération enregistrée.": "Operation recorded.",
  "Paiement immédiat (espèces ou mobile money)": "Immediate payment (cash or mobile money)",
  "Paiement mobile money": "Mobile money payment",
  "Paiement non abouti.": "Payment did not go through.",
  "Paiement échoué ou annulé.": "Payment failed or cancelled.",
  "Paramètres": "Settings",
  "Paramètres enregistrés.": "Settings saved.",
  "Partage des frais de transaction": "Transaction fee split",
  "Partenaire": "Partner",
  "Passerelle": "Gateway",
  "Payer maintenant": "Pay now",
  "Payé": "Paid",
  "Payée": "Paid",
  "Planifier automatiquement": "Schedule automatically",
  "Plus tard": "Later",
  "Premier paiement": "First payment",
  "Prix d'achat (FCFA)": "Cost price (FCFA)",
  "Prix de vente (FCFA)": "Selling price (FCFA)",
  "Prix proposé pour la commande entière (FCFA)": "Price offered for the whole order (FCFA)",
  "Produits": "Products",
  "Produits en alerte de stock": "Products low on stock",
  "Proposer un prix": "Offer a price",
  "Proposition envoyée. Votre interlocuteur doit maintenant se prononcer.": "Offer sent. It is now up to the other party to respond.",
  "Préciser la catégorie": "Specify the category",
  "Prénom": "First name",
  "Refusée": "Declined",
  "Registre du commerce (RCCM)": "Trade register (RCCM)",
  "Registre du commerce (RCCM) — optionnel": "Trade register (RCCM) — optional",
  "Reste dû": "Still owed",
  "Reste à payer": "Left to pay",
  "Retirer": "Withdraw",
  "Retirer de la caisse": "Withdraw from the till",
  "Retraits": "Withdrawals",
  "Rythme": "Pace",
  "Règlement": "Settlement",
  "Récapitulatif": "Summary",
  "Réceptionnée": "Received",
  "Réessayer": "Try again",
  "Répartition des frais": "Fee split",
  "S'il est inscrit sur Visacredit XIXA, il sera reconnu automatiquement": "If they are registered on Visacredit XIXA, they will be recognised automatically",
  "Sans lui, vos retraits seront limités à la fréquence « 1 jour ». Vous pourrez l'ajouter plus tard dans Paramètres.": "Without it, your withdrawals are limited to the “1 day” frequency. You can add it later in Settings.",
  "Se connecter": "Sign in",
  "Second téléphone (optionnel)": "Second phone (optional)",
  "Seuil d'alerte": "Low-stock threshold",
  "Solde actuel": "Current balance",
  "Solde disponible": "Available balance",
  "Stock": "Stock",
  "Stock initial": "Opening stock",
  "Suivi": "Tracking",
  "Supprimer": "Delete",
  "Supprimer cette dépense ?": "Delete this expense?",
  "Supprimer les lues": "Delete read ones",
  "Supprimer les notifications lues ?": "Delete read notifications?",
  "Sur Visacredit XIXA": "On Visacredit XIXA",
  "Tableau de bord": "Dashboard",
  "Total dû": "Total due",
  "Total à encaisser": "Total to collect",
  "Toujours clair": "Always light",
  "Toujours sombre": "Always dark",
  "Tous les 15 jours": "Every 15 days",
  "Tout supprimer": "Delete all",
  "Trouver un grossiste et passer une commande": "Find a wholesaler and place an order",
  "Téléphone": "Phone",
  "Téléphone du fournisseur": "Supplier phone",
  "Téléphone ou email de l'agrégateur": "Aggregator phone or email",
  "Une échéance est datée dans le passé : un paiement se planifie à une date à venir.": "One instalment is dated in the past: a payment must be scheduled for a future date.",
  "Validée": "Approved",
  "Ventes": "Sales",
  "Ventes aujourd'hui": "Sales today",
  "Ventes du mois": "Sales this month",
  "Vous définissez les échéances ci-dessous": "You set the instalments below",
  "Vous pourrez le renseigner plus tard dans Paramètres. Les espaces et tirets sont ignorés.": "You can add it later in Settings. Spaces and dashes are ignored.",
  "Vérification du paiement en cours…": "Verifying payment…",
  "À crédit": "On credit",
  "À la charge du client": "Charged to the customer",
  "À ma charge": "Charged to me",
  "À recevoir": "To receive",
  "Échéancier": "Payment schedule",
  "⏳ En attente": "⏳ Pending",
  "⚠️ IFU manquant": "⚠️ Missing TIN",
  "✅ Payée": "✅ Paid",
  "✅ Valider la commande": "✅ Approve the order",
  "✅ Validée": "✅ Approved",
  "✋ J'ai reçu la commande": "✋ I received the order",
  "✋ Reçue": "✋ Received",
  "✖ Annulée": "✖ Cancelled",
  "✖ Refuser le prix": "✖ Decline the price",
  "⭐ Noter le client": "⭐ Rate the customer",
  "⭐ Noter le fournisseur": "⭐ Rate the supplier",
  "💳 Agrégateur": "💳 Aggregator",
  "💳 Demander le paiement": "💳 Request payment",
  "💵 Comptant": "💵 Upfront",
  "💵 Encaisser en espèces": "💵 Collect in cash",
  "💵 Espèces": "💵 Cash",
  "💵 Payer en espèces": "💵 Pay in cash",
  "📅 À crédit": "📅 On credit",
  "📦 Commandes reçues": "📦 Orders received",
  "📦 Livrée": "📦 Delivered",
  "📦 Marquer comme livrée": "📦 Mark as delivered",
  "📱 Mobile Money (KkiaPay)": "📱 Mobile Money (KkiaPay)",

  // ── Propres à l'application mobile ─────────────────────────────────────

  // Navigation du tiroir et en-têtes
  Activité: "Activity",
  Gestion: "Management",
  Compte: "Account",
  Notations: "Ratings",
  "Ma boutique": "My shop",
  "Mes clients": "My customers",
  "Mes produits": "My products",
  "Mes ventes": "My sales",
  Rôle: "Role",
  Coordonnées: "Contact details",
  "Profil, boutique et sécurité": "Profile, shop and security",
  "Gérez votre boutique depuis votre téléphone": "Manage your shop from your phone",
  "Données de l'application": "App data",
  Stockage: "Storage",

  // Connexion et inscription
  Connexion: "Sign in",
  "Créer une boutique": "Create a shop",
  "Créer ma boutique": "Create my shop",
  "Créez votre boutique en une minute": "Create your shop in a minute",
  "Téléphone (identifiant)": "Phone (sign-in ID)",
  "Il servira d'identifiant de connexion": "It will be your sign-in ID",
  "Confirmer le mot de passe": "Confirm the password",
  "Les deux mots de passe ne correspondent pas.": "The two passwords do not match.",
  "Le mot de passe doit contenir au moins 6 caractères.":
    "The password must be at least 6 characters long.",
  "Vous vendez…": "You sell…",
  "Grossiste : vous fournissez des détaillants": "Wholesaler: you supply retailers",
  "Détaillant : vous revendez aux clients finaux": "Retailer: you resell to end customers",
  "📦 En gros": "📦 Wholesale",
  "🏪 En détail": "🏪 Retail",
  "📦 Grossiste": "📦 Wholesaler",
  "🏪 Détaillant": "🏪 Retailer",
  "📴 Fonctionne hors ligne · données sur cet appareil":
    "📴 Works offline · data on this device",

  // Actions
  Confirmer: "Confirm",
  "Confirmer l'opération": "Confirm the operation",
  Envoyer: "Send",
  Payer: "Pay",
  Terminé: "Done",
  Oui: "Yes",
  "Se déconnecter": "Sign out",
  "Se déconnecter ?": "Sign out?",
  "Vous devrez saisir à nouveau votre téléphone et votre mot de passe.":
    "You will have to enter your phone number and password again.",
  "Ajouter le client": "Add the customer",
  "Ajouter une dépense": "Add an expense",
  "Nouvelle dépense": "New expense",
  "+ Produit": "+ Product",
  "Enregistrer les modifications": "Save changes",
  "Supprimer ce client": "Delete this customer",
  "Supprimer ce client ?": "Delete this customer?",
  "Supprimer ce produit": "Delete this product",
  "Supprimer ce produit ?": "Delete this product?",
  "Supprimer toutes les notifications ?": "Delete all notifications?",
  "Tout marquer lu": "Mark all read",
  "Les notifications non lues sont conservées.": "Unread notifications are kept.",
  "Y compris celles que vous n'avez pas encore consultées.":
    "Including those you have not opened yet.",
  Réinitialiser: "Reset",
  "Réinitialiser les données ?": "Reset the data?",
  "Réinitialiser les données de démonstration": "Reset the demonstration data",
  "Tout ce que vous avez saisi sera effacé et remplacé par le jeu de démonstration d'origine. Cette action est irréversible.":
    "Everything you have entered will be erased and replaced by the original demonstration set. This action cannot be undone.",
  "Visacredit XIXA fonctionne hors ligne : vos produits, ventes, clients et commandes sont enregistrés sur cet appareil, et nulle part ailleurs. Pensez donc à ne pas désinstaller l'application sans précaution.":
    "Visacredit XIXA works offline: your products, sales, customers and orders are stored on this device, and nowhere else. So take care before uninstalling the app.",
  "📞 Appeler": "📞 Call",
  "💬 SMS": "💬 Text",

  // Recherche
  "Chercher un produit": "Find a product",
  "Que cherchez-vous ?": "What are you looking for?",
  "Recherche en cours…": "Searching…",
  "Aucun résultat": "No results",
  "Aucun grossiste ne propose cet article": "No wholesaler offers this item",
  "Chez les grossistes inscrits sur Visacredit XIXA":
    "From wholesalers registered on Visacredit XIXA",
  "Saisissez le nom d'un article pour voir quels grossistes le proposent, à quel prix et en quelle quantité.":
    "Type an item name to see which wholesalers offer it, at what price and in what quantity.",
  "🔍 Nom du produit (2 caractères minimum)": "🔍 Product name (2 characters minimum)",
  "🔍 Rechercher un client…": "🔍 Search for a customer…",
  "🔍 Rechercher un produit…": "🔍 Search for a product…",
  "Chez ": "From ",
  "De ": "From ",
  "🚚 Commander": "🚚 Order",
  "Commander hors plateforme": "Order off-platform",
  "Passez une commande auprès d'un grossiste, inscrit ou non sur Visacredit XIXA.":
    "Place an order with a wholesaler, whether or not they are on Visacredit XIXA.",

  // Produits et stock
  Quantité: "Quantity",
  "Prix unitaire": "Unit price",
  "Marge unitaire": "Unit margin",
  "Stock actuel": "Current stock",
  "Stock OK": "Stock OK",
  "⚠ Stock faible": "⚠ Low stock",
  "Valeur du stock": "Stock value",
  "Corrigez ici après un inventaire": "Correct here after a stock count",
  "En dessous de ce stock, le produit apparaît en alerte":
    "Below this level, the product is flagged as low",
  "Choisie dans le catalogue commun : c'est ce qui rend les stocks comparables d'une boutique à l'autre":
    "Chosen from the shared catalogue: this is what makes stock comparable from one shop to another",
  "Produit mis à jour.": "Product updated.",
  "Approvisionnement initial": "Opening stock purchase",
  "Montant de l'approvisionnement": "Purchase amount",
  "Une dépense est enregistrée automatiquement": "An expense is recorded automatically",
  "Apparaîtra dans vos crédits fournisseurs": "Will appear under your supplier credit",
  Achat: "Purchase",
  "Ex : Riz parfumé 25 kg": "e.g. Fragrant rice 25 kg",
  "Ex : Sac de riz 25 kg": "e.g. Bag of rice 25 kg",
  "Ex : Amina Diallo": "e.g. Amina Diallo",
  "Ex : Chez Amina": "e.g. Chez Amina",
  "Ex : 0123456789": "e.g. 0123456789",
  "Ex : Réparation de la vitrine": "e.g. Shopfront repair",
  "Appuyez sur « Modifier » pour corriger le nom, le téléphone ou l'adresse.":
    "Tap “Edit” to correct the name, phone number or address.",

  // Ventes, créances, crédits
  Vente: "Sale",
  "Vente à crédit": "Credit sale",
  "Vente soldée": "Sale settled",
  Échéances: "Instalments",
  "Échéances du reste à payer": "Instalments for the balance due",
  "Modifier l'échéancier": "Edit the schedule",
  "Échéancier mis à jour.": "Schedule updated.",
  "Reste à encaisser": "Left to collect",
  "Créances soldées": "Receivables settled",
  "Aucune créance": "No receivables",
  "Ce que vos clients vous doivent encore": "What your customers still owe you",
  "Ce que vos clients détaillants vous doivent": "What your retail customers owe you",
  "Ce que vous devez à vos fournisseurs": "What you owe your suppliers",
  "Vos clients détaillants sont à jour.": "Your retail customers are up to date.",
  "Vous n'avez rien à régler à vos fournisseurs.":
    "You have nothing to settle with your suppliers.",
  "Aucun crédit en attente": "No pending credit",
  "Régler ce crédit ?": "Settle this credit?",
  Réglés: "Settled",
  "Votre solde": "Your balance",
  "Votre solde ne couvre pas la totalité de vos crédits.":
    "Your balance does not cover all your credit.",
  "Toutes vos ventes sont soldées. Les ventes à crédit apparaîtront ici.":
    "All your sales are settled. Credit sales will appear here.",
  "Enregistrez votre première transaction pour suivre votre chiffre d'affaires.":
    "Record your first transaction to track your turnover.",
  "S'il est inscrit sur Visacredit XIXA, il verra la créance de son côté":
    "If they are registered on Visacredit XIXA, they will see the receivable on their side",
  "🏦 Payer sur le solde": "🏦 Pay from the balance",
  "💳 Réclamer le paiement": "💳 Claim the payment",
  "💵 Payé comptant": "💵 Paid upfront",
  "💳 Attente paiement": "💳 Awaiting payment",

  // Commandes
  Toutes: "All",
  Validées: "Approved",
  Livrées: "Delivered",
  Payées: "Paid",
  Annulées: "Cancelled",
  "À payer": "To pay",
  "En attente": "Pending",
  "Aucune commande dans ce statut": "No order with this status",
  "Les commandes de vos clients détaillants apparaîtront ici.":
    "Orders from your retail customers will appear here.",
  "Accepter le prix": "Accept the price",
  "Refuser le prix": "Decline the price",

  // Dépenses et retraits
  "Nombre de dépenses": "Number of expenses",
  "Total dépensé": "Total spent",
  "Dépense enregistrée.": "Expense recorded.",
  "Dépense supprimée.": "Expense deleted.",
  "Sorties d'argent de la boutique": "Money leaving the shop",
  "Enregistrez vos charges (loyer, salaires, transport…) pour connaître votre solde réel.":
    "Record your costs (rent, wages, transport…) to know your real balance.",
  "Approvisionnements auprès de vos fournisseurs": "Purchases from your suppliers",
  "Effectuer le retrait": "Make the withdrawal",
  "Montant à retirer (FCFA)": "Amount to withdraw (FCFA)",
  "Total retiré": "Total withdrawn",
  "Retraits effectués": "Withdrawals made",
  "Prélèvements sur le solde de la boutique": "Drawings on the shop balance",
  "Les prélèvements que vous effectuerez sur votre caisse apparaîtront ici.":
    "The drawings you make on your till will appear here.",
  "Ventes encaissées − dépenses − retraits déjà effectués":
    "Sales collected − expenses − withdrawals already made",
  "Fréquence habituelle": "Usual frequency",
  "Fréquence de retrait habituelle": "Usual withdrawal frequency",
  "⚠️ Registre du commerce non enregistré": "⚠️ Trade register not recorded",

  // Paiement
  Agrégateur: "Aggregator",
  "Numéro payeur": "Payer number",
  "Frais de passerelle": "Gateway fee",
  "Part à ma charge": "Share charged to me",
  "Partage personnalisé…": "Custom split…",
  "Le client paie la totalité des frais": "The customer pays all the fees",
  "Je paie la totalité des frais": "I pay all the fees",
  "Paiement encaissé.": "Payment collected.",
  "Ouverture du paiement…": "Opening payment…",
  "Ouverture du paiement KkiaPay…": "Opening KkiaPay payment…",
  "Service KkiaPay inaccessible.": "KkiaPay service unreachable.",
  "Service de paiement inaccessible.": "Payment service unreachable.",
  "Impossible de charger la page de paiement.": "Could not load the payment page.",
  "Le paiement mobile money exige une vérification auprès de la passerelle, impossible hors ligne. Enregistrez le règlement en espèces.":
    "Mobile money payment requires verification with the gateway, which is impossible offline. Record the settlement in cash.",
  "⏳ Paiement en cours de confirmation": "⏳ Payment being confirmed",
  "⏳ Paiement mobile money en attente de confirmation":
    "⏳ Mobile money payment awaiting confirmation",

  // Notations
  "Aucun avis publié": "No reviews published",
  "Aucun avis émis": "No reviews given",
  "Les avis de vos partenaires apparaîtront ici après leurs commandes.":
    "Your partners' reviews will appear here after their orders.",
  "Notez vos partenaires depuis la fiche d'une commande réceptionnée.":
    "Rate your partners from the page of an order you have received.",
  "Ce partenaire n'a pas encore été noté sur Visacredit XIXA.":
    "This partner has not been rated on Visacredit XIXA yet.",
  "Vos clients détaillants vous notent après chaque commande":
    "Your retail customers rate you after each order",
  "Vos fournisseurs vous notent après chaque commande":
    "Your suppliers rate you after each order",
  "Votre avis aide les autres boutiques de la plateforme.":
    "Your review helps the other shops on the platform.",
  "Merci pour votre note.": "Thank you for your rating.",
  "Livraison rapide, marchandise conforme…": "Fast delivery, goods as described…",
  "⭐ Voir les avis": "⭐ See the reviews",

  // Divers
  "Choisir…": "Choose…",
  "Description (optionnel)": "Description (optional)",
  "Les validations de commandes, réceptions et paiements apparaîtront ici.":
    "Order approvals, receipts and payments will appear here.",
  "Aucune option disponible.": "No option available.",
  "Suit le réglage du téléphone": "Follows the phone setting",
  "Votre Identifiant Fiscal Unique est obligatoire. Appuyez ici pour le renseigner dans Paramètres.":
    "Your Tax Identification Number is required. Tap here to fill it in under Settings.",
};
